#!/bin/sh
# Programmed by Taim Anderson

if [ $# -lt 1 ]; then
	echo "Usage: $0 vm_name"
	exit 1
fi

VM_NAME="$1"
LOG_FILENAME="$HOME/bin/cvm.log"
if [ -f $HOME/bin/def_vm.conf ]; then
	. $HOME/bin/def_vm.conf
else
	echo "Error: The configuration file $HOME/bin/def_vm.conf does not exist" > $LOG_FILENAME 2>&1
	exit 1
fi

# Create VM
echo "Creating $VM_NAME VM" > $LOG_FILENAME 2>&1
vboxmanage createvm --name "$VM_NAME" --register >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) createvm"
	echo "Error:($RET_CODE) createvm" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi

# Create IDE controller
echo "Creating IDE Controller" > $LOG_FILENAME 2>&1
vboxmanage storagectl "$VM_NAME" --name "$IDE_CTRL" --add ide >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) create ide controller"
	echo "Error:($RET_CODE) create ide controller" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi

# Create SATA controller
echo "Creating SATA Controller" > $LOG_FILENAME 2>&1
vboxmanage storagectl "$VM_NAME" --name "$SATA_CTRL" --add sata --controller IntelAHCI >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) create ide controller"
	echo "Error:($RET_CODE) create ide controller" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi

# Create HDD
echo "Creating HDD" > $LOG_FILENAME 2>&1
vboxmanage createhd --filename "$HOME/VirtualBox VMs/$VM_NAME/$VM_NAME.vdi" --size "$HDD_SIZE" >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) create hdd"
	echo "Error:($RET_CODE) create hdd" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi


# Attaching HDD
echo "Attaching HDD" > $LOG_FILENAME 2>&1
vboxmanage storageattach "$VM_NAME" --storagectl "$SATA_CTRL" --port 0 --device 0 --type hdd --medium "$HOME/VirtualBox VMs/$VM_NAME/$VM_NAME.vdi" >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) attaching hdd"
	echo "Error:($RET_CODE) attaching hdd" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi

# Modifying VM 
echo "Modifying VM" > $LOG_FILENAME 2>&1
vboxmanage modifyvm "$VM_NAME" --memory "$MEM_SIZE" --acpi on --boot1 dvd --nic1 bridged --bridgeadapter1 "$NIC_IF_NAME" --vrdeport "$VRDE_PORT" >> $LOG_FILENAME 2>&1
RET_CODE=$?
if [ $RET_CODE -ne 0 ]; then
	echo "Error:($RET_CODE) modifying VM"
	echo "Error:($RET_CODE) modifying VM" >> $LOG_FILENAME 2>&1
	exit $RET_CODE
fi
echo "Virtual Machine $VM_NAME was created."
